
import nodemailer from "nodemailer";
import { type Idea } from "@shared/schema";

/**
 * Sends an email with the generated ideas
 */
export async function sendEmailWithIdeas(
  recipientEmail: string,
  ideas: Idea[],
  prompt: string
): Promise<void> {
  try {
    const emailUser = process.env.EMAIL_USER;
    const emailPass = process.env.EMAIL_PASS;

    if (!emailUser || !emailPass) {
      throw new Error("EMAIL_USER or EMAIL_PASS environment variable is not set");
    }

    // Create a nodemailer transporter
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: emailUser,
        pass: emailPass
      }
    });

    // Create HTML content for the email
    const htmlContent = `
      <html>
        <head>
          <style>
            body {
              font-family: Arial, sans-serif;
              line-height: 1.6;
              color: #333;
              max-width: 600px;
              margin: 0 auto;
              padding: 20px;
            }
            h1 {
              color: #4F46E5;
              font-size: 24px;
              margin-bottom: 16px;
            }
            .prompt {
              background-color: #F3F4F6;
              padding: 12px;
              border-radius: 6px;
              font-style: italic;
              margin-bottom: 20px;
            }
            .idea {
              margin-bottom: 24px;
              padding: 16px;
              border-radius: 8px;
              box-shadow: 0 2px 4px rgba(0,0,0,0.1);
              background-color: #fff;
            }
            .idea-title {
              font-weight: bold;
              font-size: 18px;
              color: #4F46E5;
              margin-bottom: 10px;
            }
            .footer {
              margin-top: 30px;
              font-size: 12px;
              color: #666;
              border-top: 1px solid #eee;
              padding-top: 12px;
            }
          </style>
        </head>
        <body>
          <h1>Your Surprise Ideas</h1>
          <p>Here are your creative surprise ideas based on your prompt:</p>
          <div class="prompt">"${prompt}"</div>
          ${ideas.map((idea, index) => `
            <div class="idea">
              <div class="idea-title">${index + 1}. ${idea.title}</div>
              <p>${idea.description}</p>
            </div>
          `).join('')}
          <div class="footer">
            <p>Generated by Surprise Ideas Generator | Powered by AI</p>
            <p>© ${new Date().getFullYear()} Surprise Ideas Generator. All rights reserved.</p>
          </div>
        </body>
      </html>
    `;

    // Send the email
    const mailOptions = {
      from: `Surprise Ideas Generator <${emailUser}>`,
      to: recipientEmail,
      subject: "Your Creative Surprise Ideas",
      html: htmlContent
    };

    await transporter.sendMail(mailOptions);
  } catch (error) {
    console.error("Error sending email:", error);
    throw new Error("Failed to send email. Please try again.");
  }
}
